### ISSUE TITLE
Problem with gmp dependency

### ISSUE THREAD

**Issue by ortegafernando** [bseddon/requester#2]
Hi, there is a problem with this line "$gmp = @\gmp_import( $num );" in a shared hosting.

I am not an expert but I have read some forums in which it is said that gmp is a bit outdated (32vs64bits). They speak about using bcmath instead.

Is there any option to avoid this dependency as I can not add this extension in a shared hosting?

Thanks.

**Comment by bseddon** [comment]
There is no problem with GMP.  BCMath is not a replacement.  If you are unable to install the GMP extension, you will be unable to use this project.  I hope you are able to find a suitable alternative.

**Comment by ortegafernando** [comment]
And what about this?: https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Math/BigInteger.php  _(Uses the GMP or BCMath extensions, if available, and an internal implementation, otherwise.)_

It seems an implemantation of both GMP and BCMATH. Could it be adapted? 

I am using this library in depedency of [xml-signer](https://github.com/bseddon/xml-signer)

**Comment by bseddon** [comment]
No.  phpseclib doesn't doesn't implement a requester.  But by all means give it a go.

**Comment by ortegafernando** [comment]
> No. phpseclib doesn't doesn't implement a requester. But by all means give it a go.

Thanks a lot for your effort, best regards,
